name: CICD Django

on:
  push:
    branch:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v5.0.0

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python3 polls/tests.py

  # build:

  # deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy Via SSH
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.SSH_HOST }}
  #         username: ${{ secrets.SSH_USERNAME }}
  #         key: ${{ secrets.SSH_PRIVATE_KEY }}
  #         script: |
           